# Generated by Django 5.1.1 on 2024-10-25 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AMA', 'Amazonas'), ('ANC', 'Áncash'), ('APU', 'Apurímac'), ('ARE', 'Arequipa'), ('AYA', 'Ayacucho'), ('CAJ', 'Cajamarca'), ('CAL', 'Callao'), ('CUS', 'Cusco'), ('HUV', 'Huancavelica'), ('HUA', 'Huánuco'), ('ICA', 'Ica'), ('JUN', 'Junín'), ('LAL', 'La Libertad'), ('LAM', 'Lambayeque'), ('LIM', 'Lima'), ('LOR', 'Loreto'), ('MDD', 'Madre de Dios'), ('MOQ', 'Moquegua'), ('PAS', 'Pasco'), ('PIU', 'Piura'), ('PUN', 'Puno'), ('SAM', 'San Martín'), ('TAC', 'Tacna'), ('TUM', 'Tumbes'), ('UCA', 'Ucayali')], default='Cancel', max_length=50)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
